name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "You just submitted your first issue! We'll let you know the next steps once we've reviewed it.' first issue"
        pr-message: "Your first pull request! Wow! We'll get this added to our repository ASAP!' first pull request"
